### ISSUE TITLE
No Copper

### ISSUE THREAD

**Issue by Moquia** [TeamAOF/All-of-Fabric-3#305] opened 2021-02-27 18:42 UTC
EDIT: This is with the ecotones world generator chosen in other world options. Normal world generation does generate copper ore. Plus it seems other ores like nickel also has problems in ecotones.

I cant get copper to generate in my new world. Tried finding the ore data in the TechReborn json files but couldn't find any. I am new to this modpack stuff so probably some silly thing. Ver 2.6.10

**Comment by Monster-Zer0** [comment] 2021-03-04 18:37
sounds like an ecotones bug

**Comment by dandin87** [comment] 2021-03-11 06:23
Going to close this. Supercoder79 (ecotones dev)said the issue is with Fabric API. No ores from from TR or MI will generate in the world. Nickel is also not an ore that generates in the world in Tech Reborn or in AoF, it is a processed ore. MI quarry can however generate Nickel ore.

**Closed by dandin87** 2021-03-11 06:23 UTC
Labels: Mod Issue
