### ISSUE TITLE
Random Missing Textures

### ISSUE THREAD

**Issue by a63d** [TeamAOF/All-of-Fabric-3#311] opened 2021-03-09 20:20 UTC
There are random missing item textures. Even vanilla textures are missing. None of the missing textures are specific from what I can tell. 1.16

![image](https://user-images.githubusercontent.com/64760463/110532271-38de7780-80e2-11eb-978a-202cf1c62efb.png)

**Comment by dandin87** [comment] 2021-03-09 20:24
You either added optifine or sodium, without ready our #faqs channel on discord. we explain what is need to use those. Please do not report issues after adding mods to the pack, it means the issue is almost always with the mods you added. Closing this unless you have logs showing you did not add mods and are having this issue.

**Closed by dandin87** 2021-03-09 20:24 UTC
