### ISSUE TITLE
Hard Hat Steve armor crashes when looked at

### ISSUE THREAD

**Issue by Dunklheit** [TeamAOF/All-of-Fabric-3#207] opened 2020-11-23 14:00 UTC
Hard Hat Steve armor crashes any player that dare gazes upon its glorious armor. This includes the inventory screen, F5 and looking at other players. The crash occurs on AO3 2.4.4

**Comment by ImAK9** [comment] 2020-11-23 14:02
The log?

**Comment by Dunklheit** [comment] 2020-11-23 14:05
> The log?

I will attach a log to my original post when at my desk. Until then the issue is very easy to reproduce and if anyone would like to attach their own log file they can do so.

**Comment by dandin87** [comment] 2020-11-23 14:07
NotSteven made a modified version of Hard Hat Steve to fix this issue. Not sure why it looks like no one made an issue on their github....

**Comment by JamiesWhiteShirt** [comment] 2020-11-23 16:50
I can't resolve the issue if no one informs me of it. I'll see if I can reproduce it in an isolated case.

**Comment by dandin87** [comment] 2020-11-23 17:08
https://paste.ee/p/xchRv found the crash log. Sorry about that, I can see from the msgs that day, we were trying to find a griefer.

**Comment by JamiesWhiteShirt** [comment] 2020-11-23 19:26
Resolved in Hard Hat Steve 1.2.0, AoF3 will surely update to resolve this soon.

**Comment by Technici4n** [comment] 2020-11-23 19:32
Thanks a lot for that quick fix!

**Closed by Technici4n** 2020-11-23 19:32 UTC

**Comment by Dunklheit** [comment] 2020-11-24 00:13
@Technici4n can we keep this open until merged into 2.4.5? this would provide visibility to people who may be experiencing this issue currently and help them diagnose their crashes until the update.
