### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Weaselteat** [TeamAOF/All-of-Fabric-3#316] opened 2021-03-11 22:41 UTC
Getting this error trying to download AOF3 from CurseForge.

![image](https://user-images.githubusercontent.com/80491335/110865009-c8695f00-8277-11eb-8748-38b72684d209.png)

**Comment by sirsau** [comment] 2021-03-12 06:15
Same problem

**Comment by wolflord212312** [comment] 2021-03-12 07:05
Same

**Comment by kabadesu** [comment] 2021-03-12 07:49
We recommend using [GDlauncher](https://gdevs.io/). A lot of people are having this issue with curseforge launcher at the moment.

**Comment by ravensniper72** [comment] 2021-03-12 20:34
My entire discord server is having this issue.

**Comment by Zayyper** [comment] 2021-03-13 00:21
how can we fix this bug?

**Comment by dandin87** [comment] 2021-03-13 00:52
> how can we fix this bug?

Install and use GD Launcher https://gdevs.io/ or multiMC. Curseforge launcher has had a mess of issues since Overwolf took over. Most involving some mods not getting installed, or the wrong pack version installing instead of the latest. The issue is with Curseforge Launcher and if you want to ask them why its not working. We have and will continue to recommend users install a different launcher. GD Launcher is very similar in its ease of use and far better.

**Comment by dandin87** [comment] 2021-03-13 00:52
The pack was working fine, and then a couple days ago this issue started happening and we have not updated the pack during that time, meaning this issue is all on Curseforge and not our pack.

**Comment by Monster-Zer0** [comment] 2021-05-03 15:31
CF issue (closing)

**Closed by Monster-Zer0** 2021-05-03 15:31 UTC
