### ISSUE TITLE
Can't craft Crackers from Companion mod

### ISSUE THREAD

**Issue by Dathide** [TeamAOF/All-of-Fabric-3#206] opened 2020-11-22 22:01 UTC
The recipe in REI says two wheat horizontally to make four crackers, but that ends up making flour from Croptopia.
![2020-11-22_14 58 43](https://user-images.githubusercontent.com/47128084/99918366-908fd900-2cd3-11eb-95bb-4d884dd22f60.png)
![2020-11-22_14 58 54](https://user-images.githubusercontent.com/47128084/99918368-92599c80-2cd3-11eb-939b-8a73add63113.png)

**Comment by Technici4n** [comment] 2020-11-22 22:03
Duplicate of #140. @ImAK9 is aware of this issue, and it will be fixed soon!

**Closed by Technici4n** 2020-11-22 22:03 UTC
