### ISSUE TITLE
Crafting Golden Lasso does not trigger achievement Wonder Woman's Day Off

### ISSUE THREAD

**Issue by tyrolanuthmatar** [TeamAOF/All-of-Fabric-3#148] opened 2020-10-14 18:32 UTC
No error to observe.  Just crafted two of these things and the Achievement book does not recognize it being crafted.  No check button if it is done.

**Comment by tyrolanuthmatar** [comment] 2020-10-15 18:17
Just to add more information: This is a brand new server with latest build.  I also noticed the sever build of latest does not have the vacuum part of the achievement quest part of the book, but the single player world does.  Something tells me the single player world is updated, but the server files are not.

**Comment by Monster-Zer0** [comment] 2020-10-21 19:08
duplicate of https://github.com/TeamAOF/All-of-Fabric-3/issues/143

**Closed by Monster-Zer0** 2020-10-21 19:08 UTC
